language: java
os:
  - linux
  - osx
jdk: oraclejdk8
install: true
script: mvn install -P skip-online-tests
cache:
  directories:
  - $HOME/.m2
notifications:
  email:
    recipients:
      - nkr@niklaskr.dk
    on_success: never
    on_failure: always