name: macOS

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    strategy:
	    matrix:
            java: [ 8, 11, 13 ]
    name: Java ${{ matrix.java }}
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml